# Documentation on the kinds of information to go in this build file:
# https://docs.acquia.com/cloud-platform/develop/pipelines/yaml/
#
# See real examples on customizing pipelines:
# https://github.com/acquia/pipelines-examples

version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.0
cde-databases:
  - wcor
variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt
events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - nvm install 12
            - nvm use 12
            - composer validate --no-check-all --ansi
            - composer install --ansi
            - source ${BLT_DIR}/scripts/pipelines/setup_env
            #- npm install --global yarn
      - validate:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/validate
      # Uncomment these lines to test database updates using live content.
      # - test-updates:
      #     type: script
      #     script:
      #       - blt drupal:sync:default:site
      - setup-app:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/setup_app
      - tests:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/tests
      - build-artifact:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/build_artifact
  # Uncomment these lines if you want something to happen when a build fails
  # or when a branch is deployed.
  # fail-on-build:
  #   steps:
  #     - runonfailure:
  #         type: script
  #         script:
  #           - "echo 'This is simple echo from fail-on-build event'"
  # When a GitHub pull request is merged, this deletes the coresponding CD.
  pr-merged:
    steps:
      - deploy:
          script:
            - "echo 'Starting removal of CDE...'"
            - "if [[ ${PIPELINE_DEPLOY_VCS_PATH} == pipelines-build-pr* && ${PIPELINE_VCS_PATH} == develop ]]; then pipelines-deploy; else echo 'Skipping CDE deletion.'; fi"
  # When a GitHub pull request is closed, this deletes the coresponding CD.
  pr-closed:
    steps:
      - deploy:
          script:
            - "echo 'Starting removal of CDE...'"
            - "if [[ ${PIPELINE_DEPLOY_VCS_PATH} == pipelines-build-pr* && ${PIPELINE_VCS_PATH} == develop ]]; then pipelines-deploy; else echo 'Skipping CDE deletion.'; fi"
  post-deploy:
    steps:
      # Deploy the build artifact to a CDE. Targeting develop branch and pull requests.
      - deploy:
          script:
            - "echo 'Starting creation of WCOR CD Environment...'"
            - "if [[ ${PIPELINE_DEPLOY_VCS_PATH} == pipelines-build-pr* && ${PIPELINE_VCS_PATH} == develop ]]; then echo 'Creating CD environment for PR.' && pipelines-deploy; else echo 'Not a PR. Skipping CD environment creation.'; fi"
            - "if [[ ${PIPELINE_DEPLOY_VCS_PATH} == pipelines-build-pr* && ${PIPELINE_VCS_PATH} == develop ]]; then echo 'Setting up Drupal environment for PR.' && pipelines-sync-dbs wcor && ./vendor/bin/drush deploy -y; fi"
